### ISSUE TITLE
Figure Out Which Powershell Versions Are Supported

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/BeaKer#14]
I wrote the initial agent script on Win10 with Powershell 5.1.

We don't know what versions of Powershell the agent script is compatible with from there.

**Comment by JondHoff** [comment]
According to PSScriptAnalyzer, the agent install script commands and syntax should be compatible all the way back to 3.0 and up to 6.2. I also manually tested PS 7.1 and it worked perfectly.
