### ISSUE TITLE
unable to install BeaKer due to acmlisb.sh 

### ISSUE THREAD

**Issue by kazim-shaikh** [activecm/BeaKer#25]
Hi @activecm team,

Unable to install beaker due to below error . i downloaded the code from GIT & i dont see acmlib.sh file under any any folders . Can you assist please ?

 ./install_beaker.sh
./install_beaker.sh: line 34: ./shell-lib/acmlib.sh: No such file or directory

**Comment by ethack** [comment]
Download the latest release tar file from [this page](https://github.com/activecm/BeaKer/releases). This includes everything you need to install.

**Comment by kazim-shaikh** [comment]
@ethack Thanks !! got it
